### ISSUE TITLE
A Exception Using reader.iterable()

### ISSUE THREAD

**Issue by dysonbird** [linkedin/PalDB#16]
When i follow the code example iterate on a store, some exception occur.
The iterate code as below:
```java
Configuration config = PalDB.newConfiguration();
config.registerSerializer(new PointSerializer());
StoreReader reader = PalDB.createReader(new File("store.paldb"), config);
Iterable<Map.Entry<String, String>> iterable = reader.iterable();
for (Map.Entry<String, String> entry : iterable) {
	String key = entry.getKey();
        reader.get(key);
}
```
 *  First test case

I create a paldb like this:
```java
Configuration config = PalDB.newConfiguration();
config.registerSerializer(new PointSerializer());
StoreWriter writer = PalDB.createWriter(new File("store.paldb"), config);
for(int i = 1; i <= 10; i++) {
	Point point = new Point(i, i);
	writer.put(point.toString(), point);
}
writer.close();
```
Exception could be occur below:
```java
Exception in thread "main" java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at com.linkedin.paldb.impl.StorageReader.getDataBuffer(StorageReader.java:365)
	at com.linkedin.paldb.impl.StorageReader.getMMapBytes(StorageReader.java:292)
	at com.linkedin.paldb.impl.StorageReader.access$6(StorageReader.java:289)
	at com.linkedin.paldb.impl.StorageReader$StorageIterator.next(StorageReader.java:444)
	at com.linkedin.paldb.impl.StorageReader$StorageIterator.next(StorageReader.java:1)
	at com.linkedin.paldb.impl.ReaderIterable$ReaderIterator.next(ReaderIterable.java:83)
	at com.linkedin.paldb.impl.ReaderIterable$ReaderIterator.next(ReaderIterable.java:1)
```
 *  Second test case

I create a paldb like this:
```java
	Configuration config = PalDB.newConfiguration();
	config.registerSerializer(new PointSerializer());
	StoreWriter writer = PalDB.createWriter(new File("store.paldb"), config);
	for(int i = 1; i <= 1000; i++) {
		Point point = new Point(i, i);
		writer.put(point.toString(), point);
	}
	writer.close();
```
Exception could be occur below:
```java
Exception in thread "main" java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.linkedin.paldb.impl.ReaderIterable$ReaderIterator.next(ReaderIterable.java:89)
	at com.linkedin.paldb.impl.ReaderIterable$ReaderIterator.next(ReaderIterable.java:1)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.linkedin.paldb.utils.DataInputOutput.readUnsignedByte(DataInputOutput.java:115)
	at com.linkedin.paldb.impl.StorageSerialization.deserialize(StorageSerialization.java:834)
	at com.linkedin.paldb.impl.ReaderIterable$ReaderIterator.next(ReaderIterable.java:86)
```

I debug the code, but don't know why this happen.
I read StorageReader and do some change like below.It can avoid the exception i found, but i don't 
understand exactly.
```java
-        while (offset == 0) {
-          indexBuffer.get(currentSlotBuffer);
-          offset = LongPacker.unpackLong(currentSlotBuffer, currentKeyLength);
+        byte begin = 0;
+        while(0 == begin) {
+        	byte[] temp = new byte[1];
+        	indexBuffer.get(temp);
+        	if(temp != null) {
+        		begin = temp[0];
+        	}
         }
+        byte[] temp = new byte[currentSlotBuffer.length - 1];
+        indexBuffer.get(temp);
+        currentSlotBuffer[0] = begin;
+        System.arraycopy(temp, 0, currentSlotBuffer, 1, currentSlotBuffer.length - 1);
+        offset = LongPacker.unpackLong(currentSlotBuffer, currentKeyLength);
```

**Comment by mbastian** [comment]
This exception is due to the fact you're using `reader.get(key);` instead of `entry.getValue()` in your example. That messes up the internal index buffer position. I'll fix that.
